services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/roulette.db:/root/roulette.db
    restart: on-failure
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure